apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ProgramServiceDeployment
spec:
  selector:
    matchLabels:
      app: programservice
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: programservice
    spec:
      containers:
        - name: programservice
          image: programservice:v1.0
          ports:
            - containerPort: 8080